### ISSUE TITLE
请问Tensor.__rsub__中，other为Tensor的情况是不是写反了？

### ISSUE THREAD

**Issue by Riroaki** [tiandiweizun/autodiff#1]
https://github.com/tiandiweizun/autodiff/blob/4f39a03d32c1b46ac9f6f3ce6612d1793d1ff0b8/autodiff.py#L25

这里，RSub应该是other - self，调用sub.forward([other, self])？

**Comment by tiandiweizun** [comment]
没有写反，是这样的backward的过程呢是根据返回多少个grad，然后把对应的tensor设置的梯度加上这个grad，由于第一个是常量不存在梯度，所以如果要想放在第二个，在梯度累加的时候tensor.grad += grad[i]，要么判断这个tensor是不是常量，如果是则跳过，要么判断梯度是否为None，返回的时候可以使用占位符[None,-grad]，rsub_with_const内部梯度返回[-gard]，值为  - (self - other)

**Comment by Riroaki** [comment]
理解了，感谢！

**Comment by Riroaki** [comment]
不好意思再问一下，我觉得RSub在other为Tensor的时候应该调用的是sub.forward([other, self])？other是常数的时候我理解你的意思……

另外，什么场景会出现两个操作数都是Tensor，但是调用了__rsub__的情况呢？我觉得应该直接前者调用__sub__了吧，不会出现调用__rsub__而另一个操作数是Tensor的情况？

**Comment by tiandiweizun** [comment]
那个其实是不会触发的，如果两个都为tensor的话，会触发sub，但其实那个rsub确实写反了，只不过实际不会触发而不会产生badcase而已，我已经把__rsub__和__rtruediv__里面的为两个tensor的情况删除了。

**Comment by Riroaki** [comment]
好的，感谢你的代码😄
